Fix Typescript errors
Errors were:

src/components/ActionItem.tsx:178:50 - error TS2339: Property 'tokenAddress' does not exist on type 'CreateBotOfferTransactionsInfo'.
178             tokenAddress={action.transactionInfo.tokenAddress}
                                                     ~~~~~~~~~~~~

src/components/ActionView.tsx:171:50 - error TS2339: Property 'tokenAddress' does not exist on type 'CreateBotOfferTransactionsInfo'.
171             tokenAddress={action.transactionInfo.tokenAddress}
                                                     ~~~~~~~~~~~~