Fix Typescript error
Error was:

src/state/game/hooks.ts:283:57 - error TS2339: Property 'id' does not exist on type 'string'.
283         return challenge.recipient.toLowerCase() == val.id.toLowerCase();
                                                            ~~